# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python27
api_version: 1
threadsafe: false

handlers:
# Remote API handlers. Note that login: admin must not be specified because the
# handler performs its own authentication. /personfinder/remote_api is defined
# for google.org/personfinder, which only accepts paths starting with
# /personfinder.
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
- url: /personfinder/remote_api
  script: google.appengine.ext.remote_api.handler.application

# Administrative handlers
- url: .*/admin/send_mail
  script: send_mail.py
  login: admin

- url: /static
  static_dir: resources/static/fixed/
- url: /personfinder/static
  static_dir: resources/static/fixed/

# These are the handlers we've migrated to Django.
- url: /?
  script: wsgi.application
- url: /personfinder/?
  script: wsgi.application
- url: /setup_datastore/?
  script: wsgi.application
- url: /global/?
  script: wsgi.application
- url: /personfinder/global/?
  script: wsgi.application
- url: /global/home.html
  script: wsgi.application
- url: /personfinder/global/home.html
  script: wsgi.application
- url: /global/howto.html
  script: wsgi.application
- url: /personfinder/global/howto.html
  script: wsgi.application
- url: /global/responders.html
  script: wsgi.application
- url: /personfinder/global/responders.html
  script: wsgi.application
- url: /.*/admin.*
  script: wsgi.application
- url: /.+/d/.+
  script: wsgi.application
- url: /.*/feeds/repo.*
  script: wsgi.application
- url: /.*/sitemap.*
  script: wsgi.application
- url: /global/static.*
  script: wsgi.application
- url: /.*/tasks/process_expirations.*
  script: wsgi.application
- url: /.*/tasks/check_expired_person_records.*
  script: wsgi.application
- url: /.*/tasks/check_note_data_validity.*
  script: wsgi.application
- url: /.*/tasks/check_person_data_validity.*
  script: wsgi.application
- url: /.*/tasks/cleanup_stray_notes.*
  script: wsgi.application
- url: /.*/tasks/cleanup_stray_subscriptions.*
  script: wsgi.application
- url: /.*/tasks/sitemap_ping.*
  script: wsgi.application
# Everything else is still handled by the webapp2 app.
- url: .*
  script: main.py

libraries:
- name: django
  version: "1.11"
- name: ssl
  version: "2.7.11"
- name: lxml
  version: "3.7.3"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
