#!/usr/bin/python2.5
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Handler for Atom PFIF 1.2 person and note feeds."""

__author__ = 'kpy@google.com (Ka-Ping Yee)'

import atom
import datetime
import model
import pfif
import utils

HARD_MAX_RESULTS = 200  # Clients can ask for more, but won't get more.
MAX_SKIP = 800  # App Engine imposes a limit of 1000 on max_results + skip.
PERSON_SUBTITLE_BASE = "PFIF Person Feed generated by Person Finder at "
NOTE_SUBTITLE_BASE = "PFIF Note Feed generated by Person Finder at "

def get_latest_entry_date(entities):
    if entities:
        return max(entity.entry_date for entity in entities)
    else:
        return utils.get_utcnow()

class Person(utils.Handler):
    https_required = True

    def get(self):
        if self.config.read_auth_key_required and not (
            self.auth and self.auth.read_permission):
            self.response.set_status(403)
            self.write('Missing or invalid authorization key\n')
            return

        pfif_version = self.params.version
        atom_version = atom.ATOM_PFIF_VERSIONS.get(pfif_version.version)

        max_results = min(self.params.max_results or 10, HARD_MAX_RESULTS)
        skip = min(self.params.skip or 0, MAX_SKIP)
        # we use a member because a var can't be modified inside the closure.
        self.num_notes = 0
        if self.params.omit_notes:  # Return only the person records.
            get_notes_for_person = lambda person: []
        else:
            def get_notes_for_person(person):
                notes = model.Note.get_by_person_record_id(
                    self.subdomain, person['person_record_id'])
                notes = [note for note in notes if not note.hidden]
                records = map(pfif_version.note_to_dict, notes)
                utils.optionally_filter_sensitive_fields(records, self.auth)
                self.num_notes += len(notes)
                return records

        query = model.Person.all_in_subdomain(
            self.subdomain, filter_expired=False)
        if self.params.min_entry_date:  # Scan forward.
            query = query.order('entry_date')
            query = query.filter('entry_date >=', self.params.min_entry_date)
        else:  # Show recent entries, scanning backward.
            query = query.order('-entry_date')

        persons = query.fetch(max_results, skip)
        updated = get_latest_entry_date(persons)

        self.response.headers['Content-Type'] = 'application/xml'
        records = [pfif_version.person_to_dict(person, person.is_expired)
                   for person in persons]
        utils.optionally_filter_sensitive_fields(records, self.auth)
        atom_version.write_person_feed(
            self.response.out, records, get_notes_for_person,
            self.request.url, self.env.netloc, PERSON_SUBTITLE_BASE +
            self.env.netloc, updated)
        utils.log_api_action(self, model.ApiActionLog.READ, len(records),
                         self.num_notes)


class Note(utils.Handler):
    https_required = True

    def get(self):
        if self.config.read_auth_key_required and not (
            self.auth and self.auth.read_permission):
            self.response.set_status(403)
            self.write('Missing or invalid authorization key\n')
            return

        pfif_version = self.params.version
        atom_version = atom.ATOM_PFIF_VERSIONS.get(pfif_version.version)
        max_results = min(self.params.max_results or 10, HARD_MAX_RESULTS)
        skip = min(self.params.skip or 0, MAX_SKIP)

        query = model.Note.all_in_subdomain(self.subdomain)
        query = query.filter('hidden =', False)
        if self.params.min_entry_date:  # Scan forward.
            query = query.order('entry_date')
            query = query.filter('entry_date >=', self.params.min_entry_date)
        else:  # Show recent entries, scanning backward.
            query = query.order('-entry_date')

        if self.params.person_record_id:  # Show notes for a specific person.
            query = query.filter('person_record_id =',
                                 self.params.person_record_id)

        notes = query.fetch(max_results, skip)
        updated = get_latest_entry_date(notes)

        self.response.headers['Content-Type'] = 'application/xml'
        records = map(pfif_version.note_to_dict, notes)
        utils.optionally_filter_sensitive_fields(records, self.auth)
        atom_version.write_note_feed(
            self.response.out, records, self.request.url,
            self.env.netloc, NOTE_SUBTITLE_BASE + self.env.netloc, updated)
        utils.log_api_action(self, model.ApiActionLog.READ, 0, len(records))

class Subdomain(utils.Handler):
	https_required = False
	subdomain_required = False

	def get(self):
		# No auth_key check

		max_results = min(self.params.max_results or 10, HARD_MAX_RESULTS)
		skip = min(self.params.skip or 0, MAX_SKIP)
		atom_version = atom.EVENT_1_0

		query = model.Subdomain.all()
		

		if self.params.min_entry_date: # Scan forward.
			query = query.order('timestamp')
			query = query.filter('timestamp >=', self.params.min_entry_date)
		else: # Show recent entries, scanning backward.
			query = query.order('-timestamp')

		subdomains = query.fetch(max_results, skip)
		updated = self.get_latest_timestamp(subdomains)

		self.response.headers['Content-Type'] = 'application/xml'
		
		#records = ???
		atom_version.write_subdomain_feed(
			self.response.out, subdomains, 
			self.env.netloc, '', updated)
		#utils.log_api_action(self, model.ApiActionLog.READ, 0, len(records))

	def get_latest_timestamp(self, entities):
		if entities:
			return max(entity.timestamp for entity in entities)
		else:
			return utils.get_utcnow()

if __name__ == '__main__':
    utils.run(('/feeds/person', Person), ('/feeds/note', Note), ('/feeds/event', Subdomain))
