application: pfif-tools
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /validate
  static_files: static/validator.html
  upload: static/validator.html
- url: /diff
  static_files: static/diff.html
  upload: static/diff.html
- url: /.*
  script: wsgi.application

libraries:
- name: django
  version: "1.11"
- name: ssl
  version: "2.7.11"
