#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs all the tests.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null
$TOOLS_DIR/unit_tests
u=$?
$TOOLS_DIR/server_tests
s=$?
if [ $u -gt 0 ]; then
    echo "unit tests failed."
fi

if [ $s -gt 0 ]; then
    echo "server tests failed."
fi 

if [ $u -eq 0 -a $s -eq 0 ]; then 
    echo "Unit and server tests passed."
fi
