#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs all the tests.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

$TOOLS_DIR/lint pylint-check && $TOOLS_DIR/lint flake8-check && \
    $TOOLS_DIR/unit_tests -q && \
    $TOOLS_DIR/py3_unit_tests -q && \
    $TOOLS_DIR/server_tests -q && \
    $TOOLS_DIR/python3_compatibility_check && \
    $TOOLS_DIR/ui test && \
    echo "All tests passed."
