#!/bin/bash
# Copyright 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

cd $PROJECT_DIR

# Check the current branch.
if [ "$(hg branch)" != "release-7" ]; then
    echo "You're not in release-7 branch!"
    echo "Please move to the branch by: hg update release-7"
    exit 1
fi

# Be verbose and stop on errors.
set -ex

tools/all_tests
tools/gae update app "$@"
