#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Command-line utility: generate XML note files that can be posted to the
API to add a note to all the person records in a repo.  (We use the API
to do this rather than the import mechanism so that subscribers will get
notified; see the call to importer.import_records in api.Write.post.)

To use:

    REPO='2015-nepal-earthquake'
    /usr/bin/python tools/download_feed.py \
      --format=csv \
      --out=persons.csv \
      --min_entry_date=2010-10-01 \
      --key=$PF_KEY \
      https://www.google.org/personfinder/$REPO/feeds/person
    tools/notes_for_all_persons google.org/personfinder $USER@google.com persons.csv
    Password: <enter your ASP>

The result will be a series of files in /tmp that you can then post to
the Person Finder API to write the notes to the datastore like this:

    for i in `seq 0 100 10200`; do
      echo $i
      curl -X POST -H 'Content-type: application/xml' --data-binary @/tmp/nepal-notes.${i}.xml \
           https://www.google.org/personfinder/2015-nepal-earthquake/api/write?key=$PF_KEY
    done

"""

from model import *
import atom
import datetime
import logging
import csv
import remote_api
import sys

logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)


def all_person_record_ids(repo, batch_size=100):
    """Generates all the record IDs of persons in the given repo."""
    with open(sys.argv[3]) as f:
        reader = csv.DictReader(f)
        for row in reader:
            print row['person_record_id']
            yield row['person_record_id']

def write_notes_for_all_in_repo(
        basename, repo, date, status, text, batch_size=100):
    """Writes XML Atom feeds of notes, one for every person in the repo."""
    note_dicts = []
    for person_record_id in all_person_record_ids(repo):
        # Generate a note record ID that (a) can never collide with a future
        # generated note record ID and (b) is a function of the person record
        # ID to ensure that at most one note is created per person regardless
        # of how many times this function is executed.
        domain, id = person_record_id.split('/', 1)
        note_record_id = domain + '/note.system01-' + id
        note_dicts.append({
            'note_record_id': note_record_id,
            'person_record_id': person_record_id,
            'author_name': 'Google Person Finder',
            'source_date': date,
            'status': status,
            'text': text
        })
    for i in range(0, len(note_dicts), batch_size):
        filename = basename + '.' + str(i) + '.xml'
        file = open(filename, 'w')
        atom.ATOM_PFIF_1_4.write_note_feed(
            file,
            note_dicts[i:i + batch_size],
            url='',
            title='Notes generated by notes_for_all_persons.py',
            subtitle='',
            updated=datetime.datetime.utcnow()
        )
        file.close()
        logging.info('wrote ' + filename)

def write_notes_for_nepal():
    """Writes XML Atom feeds of notes for the Nepal reactivation."""
    message = u'''
    Another major earthquake occurred in Nepal on May 12 at 12:50 Nepali time.  Information previously entered here remains present, but may not have been updated since the more recent earthquake.  If you have new information on this person, please add a note here with their updated status.

    बैशाख २९ गते १२ बजेर ५० मिनेट जाँदा नेपालमा अर्को शक्तिशाली भूकम्प गएको छ । Person Finder मा पहिले राखिएको जानकारी अझै पनि बाँकि छ तर त्यो जानकारी ताजा नहुन सक्छ । येदि तपाईसंग कुनै व्यक्ति को बारेमा नया जानकारी छ भने कृपया त्यो व्यक्तिको रेकर्ड खोजेर त्येस्मा नया टिप्पणी थप्नुहोला ।

    नेपाल में एक और बड़ा भूकंप 12 मई को नेपाली समय में 12:50 पर आया है। व्यक्ति फाइंडर में पहले से दर्ज सूचना मौजूद है, लेकिन हाल ही में आए भूकंप के बाद शायद अपडेटेड ना  हो।  अगर आपके पास किसी व्यक्ति पर नई जानकारी है, तो कृपया यहाँ उस व्यक्ति का रिकॉर्ड खोज कर एक नोट जोड़ें नई जानकारी के साथ। 
    '''.strip()

    write_notes_for_all_in_repo(
        '/tmp/nepal-notes',
        '2015-nepal-earthquake',
        date='2015-05-12T06:50:00Z',
        status='information_sought',
        text=message
    )

if __name__ == '__main__':
    remote_api.connect(sys.argv[1], sys.argv[2], None)
    write_notes_for_nepal()
