#!/bin/bash

# To run all tests that support Python 3 so far:
#
#     tools/py3_unit_tests
#
# To run just the tests in tests/test_model.py and tests/test_indexing.py:
#
#     tools/py3_unit_tests test_model test_indexing

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

# Some tests assumes that the current directory is the root of the working
# directory.
cd "$(dirname $0)/.."

echo
echo "--- Running Python 3 unit tests"
echo "DEBUGGING LINE HERE"
echo "PYTHON3 is $PYTHON3"
TZ=UTC $PYTHON3 $TESTS_DIR/unit_tests.py --pyargs --tb=short "$@"
