#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Checks that files that have been made compatible with Python 3 don't regress
# (at least not as far as python-modernize can tell).
# We only check the files that have been made compatible; more files should be
# added to this list as we make them compatible.

python-modernize --enforce \
  app/amp_start.py \
  app/const.py \
  app/text_query.py \
  tests/test_const.py \
  tests/test_text_query.py
