#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo
echo "--- Running server tests"
# Both production App Engine and dev_appserver run in the UTC timezone.
# However, the App Engine SDK uses datetime.now(), not datetime.utcnow().  
# This means that auto_now properties will get local times when written by
# server_tests.py, but UTC times when written by the dev_appserver.  So,
# to make tests work properly, we have to set the local time zone to UTC.
TZ=UTC $PYTHON $TESTS_DIR/server_tests.py "$@"
