#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo
echo "--- Updating translations"
$TOOLS_DIR/update_messages

echo
echo "--- Running server tests"
# Setting the time zone to UTC is necessary in order for server_tests.py to
# calculate times in a way that's consistent with a running dev_appserver.
TZ=UTC $PYTHON $TESTS_DIR/server_tests.py "$@"
