#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo
echo "--- Updating translations"
$TOOLS_DIR/update_messages

echo
echo "--- Running server tests"
$PYTHON $TESTS_DIR/server_tests.py "$@"
