#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is meant for use with the Travis build (if you're a person, you
# should run tools/all_tests instead). If it's run with Python 2, it will run
# all tests; if it's run with Python 3, it will run only the tests that we
# expect to pass with Python 3 so far.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

case "${TRAVIS_PYTHON_VERSION:0:1}" in

    "2")
        $TOOLS_DIR/lint pylint-check && $TOOLS_DIR/lint flake8-check && \
            $TOOLS_DIR/unit_tests -q && \
            $TOOLS_DIR/server_tests -q && \
            $TOOLS_DIR/python3_compatibility_check && \
            echo "All Python 2.7 tests and checks passed."
        ;;
    "3")
        $TOOLS_DIR/py3_unit_tests -q && \
            $TOOLS_DIR/ui test && \
            echo "All Python 3.7 tests and checks passed."
        ;;
    *)
        echo "Unrecognized Python version from Travis: $TRAVIS_PYTHON_VERSION"
        exit 1
        ;;

esac
