#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs all the tests for either Python 2.7 or 3.7. Travis will run our tests
# under two separate environments (one with Python 2.7, one with 3.7), so we
# can't simply run all the tests at once (like we do locally with
# tools/all_tests). Instead, we have two separate paths in this file, which will
# each get executed once on Travis.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

case "$1" in

    2.7)
        $TOOLS_DIR/unit_tests -q && \
            $TOOLS_DIR/server_tests -q && \
            $TOOLS_DIR/ui test && \
            echo "All Python 2.7 tests passed."
        ;;
    3.7)
        # Travis doesn't need to use the py3_unit_tests script, because its
        # default Python version is 3 here. It'd also be inconvenient for it to
        # use the py3_ script, because that script assumes you have a PYTHON3
        # environment variable.
        $TOOLS_DIR/unit_tests -q && \
            $TOOLS_DIR/python3_compatibility_check && \
            echo "All Python 3.7 tests passed."
        ;;
    *)
        echo "Unexpected Python version: $1"
        exit 1
        ;;

esac
