#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script is to help with developing the React UI. It does two things:
# * Runs a local server (tools/ui run)
# * Does a production build of the React UI and places the JS and CSS bundles in
#   the appropriate locations in the /app directory.

set -eu

case "$1" in
"run")
    npm run --prefix ui start
    ;;
"test")
    npm run --prefix ui test
    ;;
"buildtoae")
    npm run --prefix ui build
    mkdir -p app/resources/static/fixed/ui_bundles
    mv ui/dist/*-bundle.js app/resources/static/fixed/ui_bundles/
    mv ui/dist/bundle.css app/resources/static/fixed/ui_bundles/bundle.css
    cp -r --no-clobber ui/static/static/* app/resources/static/fixed/
    ;;
"depaudit")
    npm audit --prefix ui
    ;;
*)
    echo "Specify run, test, or buildtoae."
    exit 1
    ;;
esac
