#!/bin/bash

# To run all tests:
#
#     tools/unit_tests
#
# To run just the tests in tests/test_model.py and tests/test_indexing.py:
#
#     tools/unit_tests test_model test_indexing

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

# Some tests assumes that the current directory is the root of the working
# directory.
cd "$(dirname $0)/.."

echo
echo "--- Running unit tests"
TZ=UTC $PYTHON $TESTS_DIR/unit_tests.py --pyargs --tb=short "$@"
