#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

cd $APP_DIR

# Check if anything has changed since the last update.
if [ -f messages.timestamp ]; then
    changed=$(find . ../tools/setup.py \
        \( -name '*.py' -or -name '*.html' -or -name '*.po' \) \
        -newer messages.timestamp)
else
    changed=yes
fi

# If something has changed since the last update, do the update.
if [ -n "$changed" ]; then
    django-admin.py makemessages -a -e '.py,.html,.txt' && \
        django-admin.py compilemessages && \
        touch messages.timestamp
else
    echo 'Message files are up to date.'
fi

$TOOLS_DIR/find_missing_translations
