#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Runs the lint script on every .py file in the app directory and test
# directories.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

# lint_files is an array contains all files in app_dir or tests_dir
lint_files=( $APP_DIR/*.py $TESTS_DIR/*.py )

# pfif.py is maintained by Google Person Finder and has different style
# conventions, so we don't include it.
# {array[@]} expands to all elements in the array.
# {array[@]#foo} expands to all elements in the array excluding foo.
# see http://tldp.org/LDP/abs/html/arrays.html
$TOOLS_DIR/lint ${lint_files[@]#*/pfif.py} "$@"
