#!/bin/bash
# From Google Person Finder: http://code.google.com/p/googlepersonfinder/

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

find $PROJECT_DIR -name '*.pyc' -exec rm '{}' ';'
find $PROJECT_DIR -name '*.orig' -exec rm '{}' ';'
