#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo "Erasing old coverage data..."
coverage erase > /dev/null 2>&1

echo "Running unit tests with coverage..."
$TOOLS_DIR/unit_tests --with-coverage > /dev/null 2>&1

# Run coverage testing on every python file in the root of the app directory.
# Give line numbers for missing coverage.
echo "Coverage Report:"
coverage report --show-missing --rcfile=$TOOLS_DIR/.coveragerc $APP_DIR/*.py
