#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# From Google Person Finder: http://code.google.com/p/googlepersonfinder/

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

if [ "$1" == "run" ]; then
    shift

    # Look through the arguments for an application directory.
    for arg in "$@"; do
        case "$arg" in
            (--datastore_path*) datastore_path="$arg";;
            (-*) true;;
            (*) app_dir="$arg";;
        esac
    done

    # If no datastore path was given, pick one based on the directory name.
    if [ "$datastore_path" == "" -a "$app_dir" != "" ]; then
        datastore_path="/tmp/$app_dir.datastore"
        extra_args="--datastore_path=$datastore_path"
        echo "Setting datastore_path to $datastore_path"
    fi

    # Run the appserver.
    $PYTHON $APPENGINE_DIR/dev_appserver.py --port 8000 $extra_args "$@"
else
    # Run an appcfg action.
    $PYTHON $APPENGINE_DIR/appcfg.py "$@"
fi
