#!/bin/bash
# From Google Person Finder: http://code.google.com/p/googlepersonfinder/

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo
echo "--- Running unit tests"
# TODO(samking): try to get --with-coverage to work.  If not, make a new script
# to test coverage.  Maybe coverage run foo, coverage report -m?
nosetests -d "$@"
